name: hn_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  http: ^0.12.0+2
  rxdart: ^0.22.0
  font_awesome_flutter: 8.4.0




dev_dependencies:
  url_launcher: any

  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  built_value_generator: ^6.6.0


flutter:


  uses-material-design: true


